CREATE DATABASE imagination;

USE imagination;

CREATE TABLE IF NOT EXISTS images (
    id BINARY(16) NOT NULL PRIMARY KEY,
    filename VARCHAR(255) NOT NULL DEFAULT,
    width INT UNSIGNED,
    height INT UNSIGNED,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);